### PR TITLE
Upgrade nox-poetry to use poetry 1.2 / py38+

### PR DESCRIPTION
**Pull request by staticdev**
@cjolowicz I created this proposal solution to make nox-poetry work with poetry 1.2+.

The most important problem is that a project with flake8 cannot be installed together with poetry 1.2 on python 3.7. They have unsolvable importlib_metadata restrictions. Flake8 will not create a new version to fix that, so I instead raised the minimum version of python to 3.8. This enables dependency upgrades for the foreseeable future.

### CODE REVIEW

**Comment by cjolowicz** [comment]
Thanks for working on this!

I've two issues with this:

- I don't like breaking Poetry 1.1 yet.
- I'm not comfortable dropping Python 3.7 before its EOL.

These dependencies are only used for development. Can we use environment markers to require Python 3.8? We'd lose testing for Python 3.7 though, I'm not sure how I feel about that.

As for Poetry 1.1, we'd need to find out which version we have, and use the invocation that's compatible with it.

**Comment by staticdev** [comment]
@cjolowicz I think first issue is the easier one, we can continue using `--dev` and we continue with the warning on 1.2.

For python 3.7, I argued with flake8 developers and they will not change anymore to maintain compatibility with [importlib_metadata](https://github.com/python/importlib_metadata). I am not aware of a way to restrict to python 3.8 just for dev dependencies, maybe is a good solution.

My 50 cents, there is still 7 months until EOL of Py3.7, honestly it don't think it is worth extra effort to keep support since we have Python 3.11 now and supporting 4 minor versions is already ahead of 95% of all open and closed-source projects I know. Also migration from Python 3.7 to 3.8 is very smooth compared to previous upgrades from Python I've seen before.

Of course, you are the lead here, so it is your call.

**Comment by staticdev** [comment]
UPDATE: I rebased my PR. It works now with poetry 1.0.0+ again.

**Comment by johnthagen** [comment]
FWIW, Python 3.7 goes end of life tomorrow, so perhaps `nox-poetry` can drop support then

- https://endoflife.date/python

**Comment by cjolowicz** [comment]
> FWIW, Python 3.7 goes end of life tomorrow, so perhaps `nox-poetry` can drop support then
> 
> * https://endoflife.date/python

I've added an environment marker to restrict Flake8 and plugins to Python >= 3.8, so this should no longer be an issue.

**Comment by edgarrmondragon** [comment]
Superseded by https://github.com/cjolowicz/nox-poetry/pull/1213 and https://github.com/cjolowicz/nox-poetry/pull/1225

**Pull request closed without merging**
